export const timezones = [
  { value: "America/New_York", label: "America / New York" },
  { value: "America/Detroit", label: "America / Detroit" },
  { value: "America/Kentucky/Louisville", label: "America / Kentucky / Louisville" },
  { value: "America/Kentucky/Monticello", label: "America / Kentucky / Monticello" },
  { value: "America/Indiana/Indianapolis", label: "America / Indiana / Indianapolis" },
  { value: "America/Indiana/Vincennes", label: "America / Indiana / Vincennes" },
  { value: "America/Indiana/Winamac", label: "America / Indiana / Winamac" },
  { value: "America/Indiana/Marengo", label: "America / Indiana / Marengo" },
  { value: "America/Indiana/Petersburg", label: "America / Indiana / Petersburg" },
  { value: "America/Indiana/Vevay", label: "America / Indiana / Vevay" },
  { value: "America/Chicago", label: "America / Chicago" },
  { value: "America/Indiana/Tell_City", label: "America / Indiana / Tell City" },
  { value: "America/Indiana/Knox", label: "America / Indiana / Knox" },
  { value: "America/Menominee", label: "America / Menominee" },
  { value: "America/North_Dakota/Center", label: "America / North Dakota / Center" },
  { value: "America/North_Dakota/New_Salem", label: "America / North Dakota / New Salem" },
  { value: "America/North_Dakota/Beulah", label: "America / North Dakota / Beulah" },
  { value: "America/Denver", label: "America / Denver" },
  { value: "America/Boise", label: "America / Boise" },
  { value: "America/Phoenix", label: "America / Phoenix" },
  { value: "America/Los_Angeles", label: "America / Los Angeles" },
  { value: "America/Anchorage", label: "America / Anchorage" },
  { value: "America/Juneau", label: "America / Juneau" },
  { value: "America/Sitka", label: "America / Sitka" },
  { value: "America/Metlakatla", label: "America / Metlakatla" },
  { value: "America/Yakutat", label: "America / Yakutat" },
  { value: "America/Nome", label: "America / Nome" },
  { value: "America/Adak", label: "America / Adak" },
  { value: "Pacific/Honolulu", label: "Pacific / Honolulu" }
]; 